//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


public partial class admin_menulist_edit : System.Web.SessionState.IRequiresSessionState {
protected global::System.Web.UI.HtmlControls.HtmlForm form1;
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.Profile.DefaultProfile Profile {
get {
return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
}
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
}
}
}
namespace ASP {
using System.Configuration;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Security;
using System.Web.UI.WebControls.WebParts;
using System.Collections.Generic;
using System.Web.DynamicData;
using System.Collections.Specialized;
using System.Xml.Linq;
using System.Collections;
using System.Linq;
using System.Web.UI;
using System.Web.Profile;
using System.Text;
using System.Web.UI.HtmlControls;
using System.Web.Caching;
using System;
using System.Web.UI.WebControls;
using System.Web.SessionState;
using System.ComponentModel.DataAnnotations;

public class menulist_edit_aspx : global::admin_menulist_edit {
private string Bind(string expression, string format) {
return "";
}
private string Bind(string expression) {
return "";
}
}
}
